   # This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Hugo
        run: brew install hugo
      
      - name: Create basic website
        run: hugo new site slides
      
      - name: Create mkdir
        run: mkdir slides\themes\reveal-hugo
      
      - name: Clone Reveal Theme
        run: git clone https://github.com/dzello/reveal-hugo/ slides\themes\reveal-hugo
      
      - name: cd to website
        run: cd slides |
             ls

      - name: Build website
        run: hugo
        working-directory: slides

      - name: push website
        run: git checkout gh-pages |
             git add slides/public/* |
             git commit -m "auto push from github"
        
